Repository zaproxy/zap-extensions, pull requests merged in 2018-03, with the labels that each got.

#1440 Activescan Alpha help cleanup
  src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
  src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Labels: bug

#1451 Upgrade CSP Passive Scanner Extension (Salvation 2.4.0)
  .classpath
  lib/salvation-2.3.0.jar
  lib/salvation-2.4.0.jar
  src/org/zaproxy/zap/extension/cspscanner/ContentSecurityPolicyScanner.java
  src/org/zaproxy/zap/extension/cspscanner/ZapAddOn.xml
  src/org/zaproxy/zap/extension/cspscanner/lib/salvation-2.3.0.jar
  src/org/zaproxy/zap/extension/cspscanner/lib/salvation-2.4.0.jar
Labels: enhancement

#1446 Alpha Help Tweaks
  src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
  src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
  src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Labels: enhancement

#1418 HttpsInfo New UI
  src/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
  src/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java
  src/org/zaproxy/zap/extension/httpsinfo/MenuEntry.java
  src/org/zaproxy/zap/extension/httpsinfo/ZapAddOn.xml
  src/org/zaproxy/zap/extension/httpsinfo/resources/help/contents/httpsinfo.html
Labels: enhancement

#1483 webdrivers: update geckodriver to v0.20.0
  src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
  src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
  src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Labels: waiting-for:zaproxy-team

#1484 webdrivers: update ChromeDriver to v2.36
  src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
  src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
  src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Labels: waiting-for:zaproxy-team

#1486 HttpsInfo UI Tweak
  src/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
Labels: enhancement

#1497 ascan alpha help tweaks
  src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
  src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Labels: enhancement
